version: 1

models:
  - name: raw__hedera__blocks
    description: >
      Blocks on the Hedera network that provides an extra indexing tool to native Hedera transactions.
      Blocks are not native to Hedera, but added to be compatible to EVM-style smart contracts.
      For details of blocks check HIP-415.
    columns:
      - name: count
        description: Count of transactions in the block
      - name: gas_used
        description: Sum of gas used by all transactions in the block
      - name: hapi_version
        description: Hedera API version of the block
      - name: hash
        description: Hash of the block
      - name: logs_bloom
        description: Bloom filter of the block
      - name: name
        description: Name of the block
      - name: number
        description: Index number of the block
      - name: previous_hash
        description: Hash of the previous block
      - name: size
        description: Size of the block
      - name: timestamp.from
        description: The start consensus timestamp of the block
      - name: timestamp.to
        description: The end consensus timestamp of the block

  - name: transactions
    description: >
      Transactions processed on the Hedera network.
      If a transaction was submitted to multiple nodes, the successful transaction and duplicate transaction(s) will be returned as separate entries in the response with the same transaction ID.
    columns:
      - name: bytes
      - name: charged_tx_fee
        description: The fee charged for processing the transaction
      - name: consensus_timestamp
        description: The consensus timestamp in seconds.nanoseconds. This is the unique identifier of the transaction.
      - name: entity_id
        description: The ID of the entity interacted with the transaction, if applicable, including transaction_id, topic_id, token_id, schedule_id, contract_id or file_id
      - name: max_fee
        description: The maximum transaction fee the client is willing to pay
      - name: memo_base64
        description: The memo attached to the transaction encoded in Base64 format
      - name: name
        description: Type of the transaction
      - name: node
        description: The ID of the node that submitted the transaction to the network
      - name: nonce
        description: Nonce of the transaction. Zero nonce represents user submitted transactions while a non-zero nonce is generated by main nodes
      - name: parent_consensus_timestamp
        description: The consensus timestamp of the transaction that triggered this transaction
      - name: result
        description: Whether the cryptocurrency transaction was successful or not. Takes the value "SUCCESS" or an error code
      - name: scheduled
        description: Whether the transaction is scheduled
      - name: staking_reward_transfers
        description: Transfer details for staking rewards, if any
      - name: transaction_hash
        description: The hash of the transaction
      - name: transaction_id
        description: The ID of the transaction, takes the format <sender>-<timestamp_seconds>-<imestamp_nanoseconds>
      - name: transfers
        description: Transfer details for HBAR, if any
      - name: valid_duration_seconds
        description: The seconds for which a submitted transaction is to be deemed valid beyond the start time. The transaction is invalid if consensusTimestamp is greater than transactionValidStart + valid_duration_seconds
      - name: valid_start_timestamp
        description: The timestamp at which a transaction is to be deemed valid
      - name: token_transfers
        description: Transfer details for tokens, if any

    - name: messages
    - description: >
        Messages sent to topics on the Hedera network
    - columns:
      - name: chunk_info
        description: Information of the chunk associated with the message, can be empty
      - name: consensus_timestamp
        description: The consensus timestamp of the associated transaction
      - name: message
        description: The message content
      - name: payer_account_id
        description: The account ID that paid for the transaction to submit the message
      - name: running_hash
        description: The new running hash of the topic that received the message
      - name: running_hash_version
        description: Running hash version of the topic that received the message
      - name: sequence_number
        description: The sequence number of the message relative to all other messages for the same topic
      - name: topic_id
        description: The ID of the topic the message was submitted to

  - name: raw__hedera__tokens
  - description: >
      Historical token information in a certain timestamp.
      Records are created when there is a transaction associated to the transaction,
      but the data does not necessary differ from the previous record as the transaction as the transaction may not have changed its state.
      For more details, visit: https://docs.hedera.com/hedera/sdks-and-apis/sdks/readme-1/define-a-token
  - columns:
    - name: consensus_timestamp
      description: The consensus timestamp of the token state recorded
    - name: token_id
      description: The id of the token record
    - name: auto_renew_account
      description: The auto renew account ID
    - name: auto_renew_period
      description: The period at which the auto renew account will be charged a renewal fee
    - name: created_timestamp
      description: The timestamp of when the token was created
    - name: decimals
      description: The number of decimal places a token is divisible by
    - name: deleted
      description: Whether the token is already deleted or not
    - name: expiry_timestamp
      description: The epoch at which the token should expire
    - name: fee_schedule_key
      description: The fee schedule key, if any
    - name: freeze_default
      description: The default Freeze status (frozen or unfrozen) of Hedera accounts relative to this token. If true, an account must be unfrozen before it can receive the token.
    - name: freeze_key
      description: The freeze key for the token, if specified
    - name: initial_supply
      description: The initial supply of the token
    - name: kyc_key
      description: The KYC key for the token, if specified
    - name: max_supply
      description: The maximum number of tokens that can be in circulation for fungible tokens, or the maximum number of NFTs (serial numbers) that can be minted for non-fungible tokens
    - name: memo
      description: A short publicly visible memo about the token
    - name: modified_timestamp
      description: The last time the token properties were modified
    - name: name
      description: The name of the token
    - name: pause_key
      description: The pause key for a token, if specified
    - name: pause_status
      description: Whether or not the token is paused
    - name: supply_type
      description: Supply type of the token
    - name: symbol
      description: The token symbol
    - name: total_supply
      description: The total supply of the token
    - name: treasury_account_id
      description: The treasury account of the token
    - name: type
      description: whether a token is a fungible or non-fungible token
    - name: wipe_key
      description: The wipe key for the token, if specified
    - name: admin_key._type
      description: The type of the token's admin key, if specified
    - name: admin_key.key
      description: The token's admin key, if specified
    - name: custom_fees.created_timestamp
      description: The creation timestamp of the custom fee schedule for the token, if any
    - name: custom_fees.fixed_fees
      description: The fixed fee portion of the custom fee schedule for the token, if any
    - name: custom_fees.fractional_fees
      description: The fractional fee portion of the custom fee schedule for the token, if any
    - name: supply_key._type
      description: The type of the supply key for the token, if specified
    - name: supply_key.key
      description: The supply key for the token, if specified

  - name: raw__hedera__contracts
  - description: >
      Historical contract information in a certain timestamp.
      Records are created when there is a transaction associated to the contract creation, modification or deletion,
      but the data does not necessary differ from the previous record as the transaction as the transaction may not have changed its state.
      For more details, visit: https://docs.hedera.com/hedera/sdks-and-apis/sdks/smart-contracts/create-a-smart-contract
  - columns:
    - name: consensus_timestamp
      description: The consensus timestamp of the contract state recorded, associated to the transaction
    - name: contract_id
      description: The id of the contract
    - name: admin_key._type
      description: The type of the token's admin key, if specified
    - name: admin_key.key
      description: The token's admin key, if specified
    - name: auto_renew_account
      description: The account to charge for auto-renewal of this contract
    - name: auto_renew_period
      description: The period that the instance will charge its account every this many seconds to renew
    - name: created_timestamp
      description: The timestamp of when the contract was created
    - name: deleted
      description: Whether the contract is already deleted or not
    - name: evm_address
      description: The EVM address of the contract
    - name: expiration_timestamp
      description: The timestamp of when the contract is set to expire
    - name: file_id
      description: The ID of the file that stored the contract bytecode
    - name: max_automatic_token_associations
      description: The maximum number of tokens that this contract can be automatically associated with (i.e., receive air-drops from).
    - name: memo
      description: The memo to be associated with this contract (max 100 bytes)
    - name: obtainer_id
      description: The ID of the account or contract that will receive any remaining balance when the contract is deleted
    - name: permanent_removal
      description: True when the system expires a contract
    - name: proxy_account_id
      description: The proxy account ID (disabled)
    - name: timestamp.from
      description: The start epoch for which the attributes are valid for
    - name: timestamp.to
      description: The end epoch for which the attributes are valid for
    - name: bytecode
      description: The bytecode of the contract
    - name: runtime_bytecode
      description: The runtime bytecode of the contract

  - name: raw__hedera__contract_states
  - description: >
      Historical contract state information in a certain timestamp.
      Contract state means the value of the slots in the contract.
  - columns:
    - name: address
      description: The address of the contract
    - name: contract_id
      description: The id of the contract
    - name: timestamp
      description: The timestamp of when the contract state was recorded
    - name: slot
      description: The slot number of the contract state
    - name: value
      description: The value of the slot

  - name: raw__hedera__contract_results
  - description: >
      Results of contract calls from individual transactions
  - columns:
    - name: timestamp
      description: The timestamp of when the contract result was recorded, associated to the consensus timestamp of the transaction
    - name: contract_id
      description: The id of the contract
    - name: address
      description: The hex encoded evm address of contract
    - name: amount
      description: The number of tinybars sent to the function
    - name: bloom
      description: The bloom filter for the contract
    - name: call_result
      description: The hex encoded result returned by the function
    - name: created_contract_ids
      description: Array of of smart contracts that were created by the function call.
    - name: error_message
      description: The message when an error occurs during smart contract execution
    - name: from
      description: A network entity encoded as an EVM address in hex
    - name: function_parameters
      description: The hex encoded parameters passed to the function
    - name: gas_limit
      description: The maximum units of gas allowed for contract execution
    - name: gas_used
      description: The units of gas used to execute contract
    - name: hash
      description: A hex encoded 32 byte hash and it is only populated for Ethereum transaction case
    - name: result
      description: The result of the transaction
    - name: status
      description: The status of the transaction, 0x1 for a SUCCESS transaction and 0x0 for all else
    - name: to
      description: A network entity encoded as an EVM address in hex
    - name: access_list
      description: The hex encoded access_list of the wrapped ethereum transaction
    - name: address
      description: The hex encoded evm address of contract
    - name: block_gas_used
      description: The total amount of gas used in the block
    - name: block_hash
      description: The hex encoded block (record file chain) hash
    - name: block_number
      description: The block number. Since Hedera does not have the native concept of blocks, this counts the number of record files seen since the mirror node's configured start date. This can vary between mirror nodes that use different start dates
    - name: chain_id
      description: The hex encoded chain_id of the wrapped ethereum transaction
    - name: failed_initcode
      description: The hex encoded initcode of a failed contract create transaction
    - name: gas_price
      description: The hex encoded gas_price of the wrapped ethereum transaction
    - name: logs
      description: Array of logs generated by the transaction
    - name: max_fee_per_gas
      description: The hex encoded max_fee_per_gas of the wrapped ethereum transaction
    - name: max_priority_fee_per_gas
      description: The hex encoded max_priority_fee_per_gas of the wrapped ethereum transaction
    - name: nonce
      description: The nonce of the wrapped ethereum transaction
    - name: r
      description: The hex encoded signature_r of the wrapped ethereum transaction
    - name: s
      description: The hex encoded signature_s of the wrapped ethereum transaction
    - name: state_changes
      description: Array of state changes induced by the transaction
    - name: transaction_index
      description: The position of the transaction in the block
    - name: type
      description: The type of the wrapped ethereum transaction, 0 (Pre-Eip1559) or 2 (Post-Eip1559)
    - name: v
      description: The recovery_id of the wrapped ethereum transaction

  - name: raw__hedera__contract_actions
  - description: >
      Contract call actions generated by creating, calling or Ethereum calling a contract.
  - columns:
    - name: timestamp
      description: The timestamp of when the contract action was recorded, associated to the consensus timestamp of the transaction
    - name: call_depth
      description: The nesting depth of the call
    - name: call_operation_type
      description: The type of the call operation
    - name: call_type
      description: The type of the call
    - name: caller
      description: The account calling the contract
    - name: caller_type
      description: The entity type of the caller
    - name: from
      description: The EVM address of the caller
    - name: gas
      description: Gas cost in tinybars
    - name: gas_used
      description: Gas used in tinybars
    - name: index
      description: The position of the action within the ordered list of actions
    - name: input
      description: The hex encoded input data
    - name: recipient
      description: The recipient of the call
    - name: recipient_type
      description: The entity type of the recipient
    - name: result_data
      description: The hex encoded result data
    - name: result_data_type
      description: The type of the result data
    - name: to
      description: The EVM address of the recipient
    - name: value
      description: The value of the transaction in tinybars

  - name: raw__hedera__state_proof_alphas
  - description: >
      The contents of the address book file, signature files, and record file that can be used to validate the transaction occurred on the Hedera network.
      Details: https://hedera.com/blog/introducing-state-proof-alpha
  - columns:
    - name: consensus_timestamp
      description: The timestamp of when the state proof was recorded, associated to the transaction
    - name: transaction_id
      description: The id of the transaction
    - name: address_books
      description: The network address book valid at the time of the transaction
    - name: version
      description: The record file format version, either 5 or 6
    - name: record_file.head
      description: The record file the transaction belongs to
    - name: record_file.start_running_hash_object
      description:
    - name: record_file.hashes_before
      description:
    - name: record_file.record_stream_object
      description:
    - name: record_file.hashes_after
      description:
    - name: record_file.end_running_hash_object
      description:
    - name: record_file.block_number
      description:
    - name: signature_files.0.0.3
      description: 
    - name: signature_files.0.0.4
      description:
    - name: signature_files.0.0.5
      description:
    - name: signature_files.0.0.6
      description:
    - name: signature_files.0.0.8
      description:
    - name: signature_files.0.0.9
      description:
    - name: signature_files.0.0.10
      description:
    - name: signature_files.0.0.11
      description:
    - name: signature_files.0.0.12
      description:
    - name: signature_files.0.0.13
      description:
    - name: signature_files.0.0.14
      description:
    - name: signature_files.0.0.15
      description:
    - name: signature_files.0.0.16
      description:
    - name: signature_files.0.0.17
      description:
    - name: signature_files.0.0.18
      description:
    - name: signature_files.0.0.19
      description:
    - name: signature_files.0.0.20
      description:
    - name: signature_files.0.0.21
      description:
    - name: signature_files.0.0.22
      description:
    - name: signature_files.0.0.23
      description:
    - name: signature_files.0.0.24
      description:
    - name: signature_files.0.0.25
      description:
    - name: signature_files.0.0.26
      description:
    - name: signature_files.0.0.27
      description:
    - name: signature_files.0.0.28
      description:
    - name: signature_files.0.0.29
      description:
    - name: signature_files.0.0.30
      description:
    - name: signature_files.0.0.31
      description:
